### ISSUE TITLE
Support official ESM packages?

### ISSUE THREAD

**Issue by Siilwyn** [pikapkg/analyze-npm#3]
Reading the pika website it seems packages are filtered by the `module` key which is an (unofficial) convention. This mean [dual-mode packages](https://medium.com/@giltayar/native-es-modules-in-nodejs-status-and-future-directions-part-i-ee5ea3001f71#634e) are not included in pika right? It would be good to include these.

**Comment by FredKSchott** [comment]
I'm +1 on the idea, but I'd like to see what Node's ESM support actually ends up looking like before spending too much time on it: http://2ality.com/2018/12/nodejs-esm-phases.html 

While "module" is unofficial in that Node doesn't use it, it is very much supported in the community & by all major bundlers (https://github.com/rollup/rollup/wiki/pkg.module).

If the time does come to tackle this, it's not an easy problem to solve: how does the indexer know when you have a dual-mode package just by looking at the package.json? Currently, all we have access to is the package.json metadata coming back from the registry.

Adding: Also for what it's worth, I disagree with the premise that Node's ESM support === "official" ESM support 🙃

**Comment by Siilwyn** [comment]
More info than the package metadata would be needed. With access to the file index (could use unpkg api) it is a straightforward check for a `.mjs` file with the entry name.

Afaik this convention is pretty much agreed on by now.

**Comment by FredKSchott** [comment]
@Siilwyn +1, unpkg would be a great help so that we don't need to unpack 700,000+ package tarballs. Although I'm not sure Michael would appreciate the 700,000+ requests :)

I believe part of the "new plan" is to move away from Node's current lazy import resolution where extension can be auto-detected. I'm not sure what this means for that `main` convention, but again I'd rather wait for it to bake more before taking the time to implement.

**Comment by jaydenseric** [comment]
I think this is a really important feature.

It really triggers me that [`graphql-react`](https://github.com/jaydenseric/graphql-react), despite providing *native* ESM via `.mjs` that is automatically resolved by Webpack (and tree-shaken) and Node.js (`--experimental-modules` mode) is labeled un web friendly. Users are directed to find an alternative.

The very next endorsed results are `react-apollo` and `apollo-client` which have a massive ~45 KB bundle impact (compared to `graphql-react`'s ~2.5 KB), and can't run as native ESM in Node.js.

<img width="1096" alt="screen shot 2019-01-10 at 7 33 46 pm" src="https://user-images.githubusercontent.com/1754873/50956122-07bc8980-150f-11e9-8439-2e28ab09553a.png">

After a lot of production experience shipping dual mode ESM/CJS packages I have learned it is better to not specify a `module` field. There are pretty big gotchas.

**Comment by jaydenseric** [comment]
Some more examples of dual-mode packages that Webpack tree shake just fine:

- https://www.npmjs.com/package/graphql-upload
- https://www.npmjs.com/package/extract-files

Also note that someone could publish ESM in `main` and not have a `module` field or CJS at all. It's not a common pattern, but valid for a package intended for modern browsers, Webpack or Node.js `--experimental-modules` mode. Currently Pika will report that as not supporting ESM despite *only* ESM being distributed.

No matter what the final, unflagged Node.js ESM implementation looks like, `.mjs` is certainly here to stay.

**Comment by FredKSchott** [comment]
@jaydenseric All good points. The messaging was meant to hedge this with `no "module" entrypoint detected`, which is different than `this package definitely doesn't contain any web-ready ESM`.

My overall take on all of this is:
- Node.js esm support is currently in a state of flux
- `module` is both a common practice in the community, and very easy for indexers like Pika to index
- Analyzing the contents of actual package files is currently outside the scope of this index, at least for now.
- I'm not at all opposed to exploring this in the future, once Node's ESM support reaches maturity / is no longer behind a flag.

It's also not just about the work to implement. Because "module" is frontend only for the moment, there's greater confidence that the package will run on the web. A "main" ESM file could still be Node.js only and/or not meant for bundlers, for example if it used some Node.js builtin like `fs` that doesn't translate to the web.

Again, all of this will get shaken out / clarified as Node.js support matures. Until then, if your package is ESM and meant to run on the web, I'd recommend adding a "module" entrypoint to your `package.json` regardless. Not just for `pika`, but to communicate explicit support in other tooling as well.

**Comment by Siilwyn** [comment]
Fair enough to wait this out a bit.

Though one thing I would like to point out is that only according to pika's stats page only 5% of npm modules uses the `module` entrypoint which is far from a common practice. Since the intention of pika is to find modern ESM packages and ESM is in a state of flux itself I find waiting for the removal of the flag mismatching with this 'striving forward' goal from an outsiders perspective.

Again I do understand the decision to wait.

*Edit*:
> It's also not just about the work to implement. Because "module" is frontend only for the moment, there's greater confidence that the package will run on the web.

I don't think pika is restricted to web packages is it? I find modern tree-shakeable packages for Node.js very useful too.

**Comment by FredKSchott** [comment]
@Siilwyn That's really interesting, I'm not sure if I've seen anyone do tree-shaking with Node.js before. Do you have an example / more info? Or do you just mean that modern ESM packages just seem Better™️ on Node.js? (in which case, totally agreed)

**Comment by jaydenseric** [comment]
I now consider it bad practice to specify a package `module` field.

If you do:

```
import { formatError } from 'graphql/error'
```

The package `module` and `main` fields are useless to solving the problem of loading either ESM or CJS. `.mjs` resolving before `.js` solves this problem.

The `module` field was invented so Webpack (and other bundlers) can consume ESM to treeshake. Using `.mjs`/`.js` removes the need for that field, so why use it? I used to keep it (pointing to the `index.mjs`) around as a nice signal to the wider ecosystem, but my users encountered gotchas.

What was happening, was people would manually setting [`resolve.extensions`](https://webpack.js.org/configuration/resolve/#resolve-extensions) for things like `.jsx` and `.ts`, not realizing that they needed to include `.mjs`, and at the start. Even tho they might not have `.mjs` in their project files, dependencies such as `extract-files` in `node_modules` do. The result would be Webpack would see an import from `extract-files`, look at the `package.json` and see a `module` field pointing at `lib/index.mjs`, and then attempt to process the ESM imports in that file. Because the `.mjs` is missing from the `resolve.extensions` config, Webpack would attempt to resolve the `.js` files (containing CJS) instead of `.mjs` files containing ESM. This would result in module default and named import interop failure, etc.

For a while I tried to educate them about their bad config each time, but in the end it was easier to remove the `module` field and let them bundle CJS without errors.

I think Pika is a cool idea. Perhaps the solution is for npm to improve their registry to include a list of files in each package, which would also be useful for all sorts of other things.

**Comment by Siilwyn** [comment]
@FredKSchott I've seen it in cases where size matters more than usual e.g: IoT devices, serverless & CLI apps. For serverless there is: https://github.com/serverless-heaven/serverless-webpack and for CLIs: https://github.com/zeit/ncc (though I'm not sure it tree-shakes). Also in 'old school' cases, on a slow internet connection it is nice to keep the size down so when uploading to a server it is as fast as possible.

And yes I totally agree with you that modern ESM packages just seem Better:tm:.

:)

**Comment by FredKSchott** [comment]
@Siilwyn those are great examples, I always personally struggle with whether a published package should minified (smaller footprint) or not (clearer debugging/stack traces). 

@jaydenseric again, until finalized I disagree with the premise that following Node's experimental, still-behind-a-flag conventions is right & not following them = "bad config".

I have another project that I'm hoping to open source this weekend / next week that leverages "module" for a different reason (and clearly that's a piece of my bias). I'd love to get both of your thoughts on it once it's public, if you're still interested.

**Comment by FredKSchott** [comment]
Thanks for the conversation here, everyone.

**Comment by Siilwyn** [comment]
Guessing the new project is @pika/web? Congrats on the release!

This issue is still relevant in the future though right or do you think it will never happen?

**Comment by FredKSchott** [comment]
Thanks! The latest that I’ve seen is that node will use a “type” property in the package.json manifest, but as always it’s still being fleshed out & agreed to. So there’s not much to do now.

Willing to reopen when that’s finalized, but again I disagree with the premise of the ticket (that node support somehow === official support)

**Comment by devsnek** [comment]
popping in a bit late, pika should probably avoid suggesting that packages use the `module` field as its kind of overrun with babel esm which is /not/ compatible with real esm. this is the reason node itself is not using the `module` field in its esm resolution algorithm.

that's not to say some new field will pop up, just that mjs + no module field is actually a better signal of proper compat than using a module field is.
